name: smh
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ffmpeg=6.0.0
  - librosa=0.10.1
  - pip:
      - click==8.1.7
      - h5py==3.10.0
      - kornia==0.7.0
      - numpy==1.24.4
      - opencv-python-headless==4.9.0.80
      - pandas==2.1.1
      - seaborn==0.13.0
      - torch==2.1.0
      - tqdm==4.66.1
      - ultralytics==8.2.99
      - essentia==2.1b6.dev1110
