python -m smh.features.homography examples/epic2016/Source_Videos/Biking_0p.mp4
python -m smh.features.homography examples/epic2016/Source_Videos/Biking_25p.mp4
python -m smh.features.homography examples/epic2016/Source_Videos/Biking_50p_2.mp4
python -m smh.features.homography examples/epic2016/Source_Videos/Biking_50p.mp4
python -m smh.features.homography examples/epic2016/Source_Videos/Driving_0p.mp4
python -m smh.features.homography examples/epic2016/Source_Videos/Driving_25p.mp4
python -m smh.features.homography examples/epic2016/Source_Videos/Driving_50p.mp4
python -m smh.features.homography examples/epic2016/Source_Videos/Walking_0p.mp4
python -m smh.features.homography examples/epic2016/Source_Videos/Walking_25p.mp4
python -m smh.features.homography examples/epic2016/Source_Videos/Walking_50p.mp4
python -m smh.features.homography examples/epic2016/Source_Videos/Walking_75p.mp4
